package org.cts.housingaid.enums;

public enum NotificationCategory {
    HOUSINGAPPLICATION, ALLOCATION, AUDIT, AUDITLOG, CITIZEN, CITIZENDOCUMENT, CITIZENRECORD,
    ELIGIBILITYCHECK, HOUSINGPROJECT, HOUSINGUNIT, REPORT, RESOURCES, USERS
}
